version: '3.4'

volumes: 
  seq-data:

services:
  bot:
    image: mo.discordbot
    container_name: mo.discordbot
    restart: unless-stopped
    build:
      context: .
      dockerfile: Bot/Dockerfile
    env_file:
      - .env
    depends_on: 
      - seq
  
  seq:
    image: datalust/seq
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      
    volumes:
      - seq-data:/data
    
    ports:
      - "9997:80"
