version: '3.4'

volumes: 
  seq-data:
    
networks:
  postgres:
  seq:

services:
  bot:
    image: mo.discordbot
    container_name: mo.discordbot
    restart: unless-stopped
    build:
      context: .
      dockerfile: Bot/Dockerfile
    env_file:
      - .env