using Disqord;

namespace Data.Entities.Discord;

public interface IDiscordEntity
{
    /// <summary>
    /// The discord snowflake id of this <see cref="IDiscordEntity"/>.
    /// They are not meant to be generated by the database.
    /// </summary>
    public Snowflake Id { get; set; }
}